# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Publish .NET Core Project
        run: dotnet publish AuthSystem.csproj -c Release -o release --nologo
